using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using System.IO;
using System;

public abstract class FileGenerator
{
    protected int scope;
    protected string fileText;

    public void GenerateFile(string fileName)
    {
        var sw = new StreamWriter(fileName);
        fileText = $"// do not edit this file manually, it was generated procedurally from {this.GetType()}.\n"
            + $"// Generated at: {DateTime.Now}\n\n";
        GenerateFileText();
        sw.Write(fileText);
        sw.Close();
    }

    protected abstract void GenerateFileText();
}
