// do not edit this file manually, it was generated procedurally from MarchingCubeUVLookupGenerator+CSLookup.
// Generated at: 2022-06-12 9:19:00 PM

using UnityEngine;

namespace WorldGen
{
    public class MarchingCubeUVLookup
    {
        public enum TerrainType
        {
            None,
            Grass,
            Dirt,
        }
        
        public static Vector2[,] terrainCombinations = new Vector2[,]
        {
            {
                new Vector2(0.1666667f, 0.1666667f), // None + None | pixel (0, 0)
                new Vector2(0.1666667f, 0.5f), // None + Grass | pixel (0, 1)
                new Vector2(0.1666667f, 0.8333333f), // None + Dirt | pixel (0, 2)
            },
            {
                new Vector2(0.1666667f, 0.5f), // Grass + None | pixel (0, 1)
                new Vector2(0.1666667f, 0.5f), // Grass + Grass | pixel (0, 1)
                new Vector2(0.5f, 0.8333333f), // Grass + Dirt | pixel (1, 2)
            },
            {
                new Vector2(0.1666667f, 0.8333333f), // Dirt + None | pixel (0, 2)
                new Vector2(0.5f, 0.8333333f), // Dirt + Grass | pixel (1, 2)
                new Vector2(0.1666667f, 0.8333333f), // Dirt + Dirt | pixel (0, 2)
            },
        };
    }
}
